# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: taskmanager-ingress
#   namespace: {{ .Values.namespace }}
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#     - host: taskmanager.local
#       http:
#         paths:
#           - path: /frontend
#             pathType: Prefix
#             backend:
#               service:
#                 name: frontend
#                 port:
#                   number: 80
#           - path: /api
#             pathType: Prefix
#             backend:
#               service:
#                 name: backend
#                 port:
#                   number: 80
