apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskmanager.backendServiceName" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: {{ .Values.backend.port }}
