apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskmanager-prod
  annotations:
     argocd.argoproj.io/webhook: "github"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/OletiSatishKumar/Devops_Automation_Infra.git'
    targetRevision: HEAD
    path: helm/taskmanager
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
