namespace: prod-namespace

frontend:
  image: satishosk/taskmanager-frontend:main-20250607-1751
  replicas: 2
  port: 3000
  nodePort: 30200

backend:
  image: satishosk/taskmanager-backend:main-20250607-1751
  replicas: 2
  port: 8000
  mongoSecretName: mongodb-prod-secret

mongodb:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80