namespace: prod-namespace

frontend:
<<<<<<< HEAD
  image: satishosk/taskmanager-frontend:main-20250607-1751
  replicas: 2
=======
  image: satishosk/taskmanager-frontend:main-20250610-0934
  replicas: 1
>>>>>>> f0a58764a45053d6a75728bd45da0399d2b45f09
  port: 3000
  nodePort: 30200

backend:
<<<<<<< HEAD
  image: satishosk/taskmanager-backend:main-20250607-1751
  replicas: 2
=======
  image: satishosk/taskmanager-backend:main-20250610-0934
  replicas: 1
>>>>>>> f0a58764a45053d6a75728bd45da0399d2b45f09
  port: 8000
  mongoSecretName: mongodb-prod-secret

mongodb:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80