namespace: prod-namespace

frontend:
  image: satishosk/taskmanager-frontend:main-20250607-0712
  replicas: 2
  port: 3000

backend:
  image: satishosk/taskmanager-backend:main-20250607-0712
  replicas: 2
  port: 8000
  mongoUri: mongodb+srv://taskuser:taskpass@cluster0.mongodb.net/taskdb?retryWrites=true&w=majority

mongodb:
  enabled: false
