namespace: dev-namespace

frontend:
  image: satishosk/taskmanager-frontend:dev-20250607-1751
  replicas: 1
  port: 3000
  nodePort: 30080

backend:
  image: satishosk/taskmanager-backend:dev-20250607-1751
  replicas: 1
  port: 8000
  mongoSecretName: mongodb-dev-secret

mongodb:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80