apiVersion: v1
kind: Secret
metadata:
  name: mongodb-prod-secret
  namespace: prod-namespace
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9TYXRpc2hLdW1hcjpTYXRpc2glNDAlNDAxMzAzQGNsdXN0ZXIwLjhoN2l4Lm1vbmdvZGIubmV0L3Rhc2tzP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQo=
